version: "3"
services: 
  mongo:
    container_name: mongo-container
    image: mongo:5
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:16.16.0
    working_dir: /app
    restart: always
    command: bash -c "npm set-script prepare "" && npm install --omit=dev && npm run debug"
    volumes:
      - ./dist:/app/dist/
      - ./package.json:/app/package.json
    ports: 
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo