version: "3"
services: 
  mongo:
    container_name: mongo-container
    image: mongo:5
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:14
    working_dir: /app
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    environment:
      - HUSKY=0
    volumes:
      - ./dist/:/app/dist/
      - ./package.json:/app/package.json
    ports: 
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo